### ISSUE TITLE
SyntaxError: Cannot use import statement outside a module when using RDF-EXT with JEST

### ISSUE THREAD

**Issue by MMesch** [rdf-ext/rdf-ext#114]
I'm more or less running into a problem with ESM vs CJS as described in issue #93 when using `rdf-ext` as dependency and running `jest` + `ts-jest` over it. The error I get is:

```
> jest

 FAIL  src/lib.test.ts
  ● Test suite failed to run

    Jest encountered an unexpected token

    Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.

    Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.

    By default "node_modules" folder is ignored by transformers.

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/ecmascript-modules for how to enable it.
     • If you are trying to use TypeScript, see https://jestjs.io/docs/getting-started#using-typescript
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/configuration
    For information about custom transformations, see:
    https://jestjs.io/docs/code-transformation

    Details:

    /home/x/x/x/x/node_modules/rdf-ext/index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){import Environment from '@rdfjs/environment/Environment.js'
                                                                                      ^^^^^^

    SyntaxError: Cannot use import statement outside a module

      1 | import {type Quad} from 'quadstore';
      2 | import {Parser} from 'n3';
    > 3 | import rdf from "rdf-ext";
        | ^
      4 |
      5 | ...

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1505:14)
      at Object.<anonymous> (src/lib.ts:3:1)
      at Object.<anonymous> (src/lib.test.ts:3:1)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        0.545 s
Ran all test suites.
```

My jest config looks like this:

```
/** @type {import('ts-jest').JestConfigWithTsJest} **/
module.exports = {
  testEnvironment: "node",
  transform: {
    "^.+.tsx?$": ["ts-jest",
		{useESM: true,
		 isolatedModules: true,}],
  },
  moduleDirectories: ["node_modules", "src", "test"]
};
```

Testing works fine with other dependencies (e.g. quadstore and n3 in the example above) as long as no `rdf-ext` is involved. So far, all my attempts to fix this have failed. Any ideas?

**Comment by MMesch** [comment]
`"test": "node --experimental-vm-modules node_modules/jest/bin/jest.js",`

This line fixed it for me.
